### PR TITLE
Set --source and --target when available.

### LINKED ISSUE #1: Support for --source and --target in JavaBuild::compile()
Hi,

I am trying to compile your excellent `robius-authentication` crate for android using a Flutter/Android Studio setup and I am getting a class version mismatch.

I ***think*** it is because in the Android Studio gradle config I have:

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
```

But when `JavaBuild::compile()` is executed it uses the latest available version (21) yielding this error:

```
SEVERE:   Error in /Users/muji/git/sos/local_auth/build/rust_lib_local_auth/build/aarch64-linux-android/debug/build/robius-authentication-3a6eb04dd668c228/out/robius/authentication/AuthenticationCallback.class:
SEVERE:   java.lang.IllegalArgumentException: Unsupported class file major version 65
```

I really don't want to change the version in Android Studio as it will likely wreak havoc with other dependencies so I wonder if it makes sense to add a couple more environment variables to `android-build` so we can specify the source and target compile versions?

Perhaps `ANDROID_SOURCE_VERSION` and `ANDROID_TARGET_VERSION` could be translated to the `--source` and `--target` javac options?

I don't think it's feasible to set `JavaBuild::command()` directly as `android-build` is a transient dependency of `robius-authentication` in this case.

FWIW, these are the configured environment variables (trying to ensure that `android-build` uses the same JDK as Android Studio):

```
export ANDROID_JAR="$ANDROID_SDK/platforms/android-34/android.jar"
export ANDROID_SDK_ROOT="$ANDROID_SDK"
export ANDROID_D8_JAR="$ANDROID_SDK/build-tools/34.0.0/lib/d8.jar"
export ANDROID_BUILD_TOOLS_VERSION="34.0.0"
export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
```

Happy to contribute a PR if you think this approach is correct, thanks 🙏

### PR DESCRIPTION
**Pull request by tmpfs**
From the `ANDROID_SOURCE_VERSION` and `ANDROID_RELEASE_VERSION` environment variables.

Closes #1.

### CODE REVIEW

File: src/env_paths/mod.rs [hunk 1]
```diff
@@ -1,25 +1,31 @@
...
-pub const ANDROID_PLATFORM:             &str = "ANDROID_PLATFORM";
-pub const ANDROID_SDK_VERSION:          &str = "ANDROID_SDK_VERSION";
-pub const ANDROID_API_LEVEL:            &str = "ANDROID_API_LEVEL";
-pub const ANDROID_SDK_EXTENSION:        &str = "ANDROID_SDK_EXTENSION";
-pub const ANDROID_D8_JAR:               &str = "ANDROID_D8_JAR";
-pub const ANDROID_JAR:                  &str = "ANDROID_JAR";
-pub const JAVA_HOME:                    &str = "JAVA_HOME";
-
+pub const ANDROID_SOURCE_VERSION: &str = "ANDROID_SOURCE_VERSION";
+pub const ANDROID_TARGET_VERSION: &str = "ANDROID_TARGET_VERSION";
```
Comment (kevinaboos) [inline src/env_paths/mod.rs]: kindly follow our existing indentation/alignment scheme here, thanks

**Review by kevinaboos — CHANGES_REQUESTED** [review]
Thanks, this looks good to me. 

Can you undo all of the unrelated changes? I assume you ran a code formatter like rustfmt, but for this PR let's just restrict the changes to those relevant for `--source` and `--target`. Thanks!

Also, please add a description of the two new env vars to the crate-level documentation such that they appear [here](https://docs.rs/android-build/latest/android_build/#environment-variables-in-use)

**Comment by tmpfs** [comment]
Ah yeh, sorry about that @kevinaboos - my neovim config does that by default. I switched to vim and have addressed all your points and force pushed, I think it follows the convention now.

The diff is much clearer now 👍

**Comment by kevinaboos** [comment]
Thanks, looks good now! One more request -- can you give some examples (in the docs) of what sort of values/formats are supported for the new `--source`/`--target` arguments? I'm not familiar with them, but I assume it's something like "--source 1.7". 

(Note that in the crate-level docs I gave similar examples for android versions, since they can be confusing).

**Comment by kevinaboos** [comment]
Ah, actually, a couple more comments:

1. Are these source and target versions related to Android at all? They seem to be exclusively related to _Java_, not Android per se. If that's the case, we should name them accordingly: `JAVA_SOURCE_VERSION` and `JAVA_TARGET_VERSION`
2. Is it "target" or "release"? In your PR description, you wrote "ANDROID_RELEASE_VERSION" but I assume you mean "target".

**Comment by tmpfs** [comment]
Ah, good points. Yes it's actually more Java related so I will rename them. Will add examples too, should be something like "17". I do find the Java versioning crazy confusing though 😆

**Comment by tmpfs** [comment]
Correct @kevinaboos, using `RELEASE` in the issue was a mistake we should use SOURCE and TARGET so it matches the `javac` options.

I've switched to the `JAVA` prefix for the variables and clarified in the docs to use `17` which is the language version (corresponding to JDK 1.7 I think), do you think this is ok now?

**Review by kevinaboos — APPROVED** [review]
yep, looks good now. Thanks for the contributions!
